import { Logger } from '@nestjs/common';
import { AttachmentEntityType } from '@db';
import { AttachmentsService } from '../../attachments/attachments.service';

type CellRow = (string | number)[];

const logger = new Logger('SheetAttachmentUtil');

export function buildCsv(
  headers: CellRow | undefined,
  rows: CellRow[],
): string {
  const allRows: CellRow[] = [...(headers ? [headers] : []), ...rows];
  return allRows.map(csvRow).join('\r\n');
}

function csvRow(row: CellRow): string {
  return row.map(csvField).join(',');
}

function csvField(value: string | number): string {
  if (typeof value === 'number') {
    return String(value);
  }
  if (
    value.includes(',') ||
    value.includes('"') ||
    value.includes('\n') ||
    value.includes('\r')
  ) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function sanitizeFileName(name: string): string {
  return name.replace(/[/\\:*?"<>|]/g, '_');
}

function truncate(value: string, max: number): string {
  return value.length <= max ? value : value.slice(0, max);
}

export async function attachSheetAsCsv({
  attachmentsService,
  organizationId,
  taskId,
  automationId,
  title,
  spreadsheetUrl,
  headers,
  rows,
}: {
  attachmentsService: AttachmentsService;
  organizationId: string;
  taskId: string;
  automationId: string;
  title: string;
  spreadsheetUrl: string;
  headers?: CellRow;
  rows: CellRow[];
}): Promise<boolean> {
  try {
    const csv = buildCsv(headers, rows);
    const fileData = Buffer.from(csv, 'utf-8').toString('base64');
    const fileName = `${truncate(sanitizeFileName(title), 251)}.csv`;
    const rawDescription = `Generated by automation ${automationId} — ${spreadsheetUrl}`;
    const description = truncate(rawDescription, 500);

    await attachmentsService.uploadAttachment(
      organizationId,
      taskId,
      AttachmentEntityType.task,
      { fileName, fileType: 'text/csv', fileData, description },
    );
    return true;
  } catch (err) {
    logger.error(
      `Failed to attach CSV for task ${taskId} automation ${automationId}: ${err instanceof Error ? err.message : String(err)}`,
    );
    return false;
  }
}
